# Generated by Django 5.1.4 on 2025-01-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0002_tipousuario_alter_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ingresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('monto', models.FloatField()),
                ('tipo_ingreso', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name': 'ingreso',
                'verbose_name_plural': 'ingresos',
                'db_table': 'ingresos',
            },
        ),
    ]
