# Generated by Django 5.1.4 on 2025-01-06 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0003_ingresos'),
    ]

    operations = [
        migrations.CreateModel(
            name='egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('monto', models.FloatField()),
                ('tipo_ingreso', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name': 'egreso',
                'verbose_name_plural': 'egresos',
                'db_table': 'egresos',
            },
        ),
        migrations.CreateModel(
            name='extras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('monto', models.FloatField()),
                ('fecha', models.DateField()),
                ('egreso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gimnasio.egreso')),
                ('ingreso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gimnasio.ingresos')),
            ],
            options={
                'verbose_name': 'extra',
                'verbose_name_plural': 'extras',
                'db_table': 'extras',
            },
        ),
    ]
