# Generated by Django 5.1.4 on 2025-01-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0005_cuota_gimnasio_egreso_gimnasio_extras_gimnasio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='efectivo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='precio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='tarjeta_credito',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='transferencia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='egreso',
            name='monto',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extras',
            name='monto',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='monto',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
