# Generated by Django 5.1.4 on 2025-01-09 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0006_alter_cuota_efectivo_alter_cuota_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='gimnasio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cuota', to='gimnasio.gimnasio'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='gimnasio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='gimnasio.gimnasio'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='gimnasio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='venta', to='gimnasio.gimnasio'),
        ),
    ]
