# Generated by Django 5.1.4 on 2025-01-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0008_cuota_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
