# Generated by Django 5.1.4 on 2025-01-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0009_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='efectivo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='tarjeta_credito',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='transferencia',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
