# Generated by Django 5.1.4 on 2025-01-16 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0010_venta_efectivo_venta_tarjeta_credito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extras',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extras', to='gimnasio.producto'),
        ),
    ]
