# Generated by Django 5.1.4 on 2025-01-16 13:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0011_extras_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='extras',
            name='hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
