# Generated by Django 5.1.4 on 2025-01-21 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0013_balancediario'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='clases_restantes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='socio',
            name='tipo_mensualidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gimnasio.tipomensualidad'),
        ),
    ]
