# Generated by Django 5.1.4 on 2025-01-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0015_registroingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
