# Generated by Django 5.1.4 on 2025-01-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0016_socio_fecha_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroingreso',
            name='clases_restantes_al_ingresar',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
