# Generated by Django 5.1.4 on 2025-01-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0017_registroingreso_clases_restantes_al_ingresar'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroingreso',
            name='apellido_socio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registroingreso',
            name='nombre_socio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
