# Generated by Django 5.1.4

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0018_registroingreso_apellido_socio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMensualidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría de Mensualidad',
                'verbose_name_plural': 'Categorías de Mensualidad',
                'db_table': 'CategoriaMensualidades',
            },
        ),
        migrations.AddField(
            model_name='tipomensualidad',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_mensualidad', to='gimnasio.categoriamensualidad'),
        ),
        migrations.AddField(
            model_name='tipomensualidad',
            name='clases_incluidas',
            field=models.PositiveIntegerField(blank=True, help_text='Cantidad de clases si es por clases', null=True),
        ),
        migrations.AddField(
            model_name='tipomensualidad',
            name='frecuencia',
            field=models.CharField(blank=True, choices=[('3x_semana', '3 veces por semana'), ('todos_dias', 'Todos los días'), ('2x_semana', '2 veces por semana'), ('1x_semana', '1 vez por semana'), ('clases', 'Por clases (cantidad fija)'), ('pase_libre', 'Pase libre')], default='pase_libre', max_length=50, null=True),
        ),
    ]
