# Generated by Django 5.1.4

from django.db import migrations


def crear_categorias(apps, schema_editor):
    # Sin datos de ejemplo: cada gimnasio crea sus planes desde la app.
    pass


def reverse_categorias(apps, schema_editor):
    CategoriaMensualidad = apps.get_model('gimnasio', 'CategoriaMensualidad')
    CategoriaMensualidad.objects.filter(nombre__in=['TAEBO', 'SALSA', 'PESAS']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0019_categoriamensualidad_and_more'),
    ]

    operations = [
        migrations.RunPython(crear_categorias, reverse_categorias),
    ]
