# Generated by Django 5.1.4

from django.db import migrations


def crear_tipos_usuario(apps, schema_editor):
    TipoUsuario = apps.get_model('gimnasio', 'TipoUsuario')
    for nombre in ['super_usuario', 'admin', 'empleado']:
        TipoUsuario.objects.get_or_create(tipousuario=nombre)


def reverse_tipos(apps, schema_editor):
    pass  # No revert - tipos podrían estar en uso


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0020_categorias_iniciales'),
    ]

    operations = [
        migrations.RunPython(crear_tipos_usuario, reverse_tipos),
    ]
