# Generated by Django 5.1.4

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0021_tipos_usuario_iniciales'),
    ]

    operations = [
        migrations.AddField(
            model_name='gimnasio',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='UsuarioGimnasio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gimnasio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_asignados', to='gimnasio.gimnasio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gimnasios_asignados', to='gimnasio.usuario')),
            ],
            options={
                'db_table': 'UsuarioGimnasios',
                'unique_together': {('usuario', 'gimnasio')},
            },
        ),
        migrations.AddField(
            model_name='categoriamensualidad',
            name='gimnasio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias_mensualidad', to='gimnasio.gimnasio'),
        ),
        migrations.AddField(
            model_name='registroingreso',
            name='gimnasio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_ingreso', to='gimnasio.gimnasio'),
        ),
        migrations.AlterUniqueTogether(
            name='categoriamensualidad',
            unique_together={('gimnasio', 'nombre')},
        ),
    ]
