# Generated by Django 5.1.4

from django.db import migrations


def migrar_datos(apps, schema_editor):
    CategoriaMensualidad = apps.get_model('gimnasio', 'CategoriaMensualidad')
    UsuarioGimnasio = apps.get_model('gimnasio', 'UsuarioGimnasio')
    Gimnasio = apps.get_model('gimnasio', 'Gimnasio')
    Usuario = apps.get_model('gimnasio', 'Usuario')

    # Asignar categorías sin gym al primer gimnasio
    primer_gym = Gimnasio.objects.first()
    if primer_gym:
        CategoriaMensualidad.objects.filter(gimnasio__isnull=True).update(gimnasio=primer_gym)

    # Vincular cada usuario con todos los gimnasios existentes
    for usuario in Usuario.objects.all():
        for gym in Gimnasio.objects.all():
            UsuarioGimnasio.objects.get_or_create(usuario=usuario, gimnasio=gym)


def reverse_migrar(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0022_multigym'),
    ]

    operations = [
        migrations.RunPython(migrar_datos, reverse_migrar),
    ]
