# Generated by Django 5.1.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0023_datos_multigym'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='nombre_titular_transferencia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
