# Generated by Django 5.1.4 on 2026-03-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0025_add_gasto_and_venta_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='nombre_titular',
            field=models.CharField(blank=True, help_text='Titular de transferencia o tarjeta', max_length=255, null=True),
        ),
    ]
