# Generated by Django 5.1.4 on 2026-03-03 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0026_venta_nombre_titular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('monto_inicial', models.FloatField(blank=True, default=0)),
                ('gimnasio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajas', to='gimnasio.gimnasio')),
                ('usuario_apertura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cajas_abiertas', to='gimnasio.usuario')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'db_table': 'cajas',
            },
        ),
    ]
