# Generated by Django 5.1.4 on 2026-03-04 15:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0027_caja_diaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('gimnasio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesores', to='gimnasio.gimnasio')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'db_table': 'Profesores',
            },
        ),
        migrations.CreateModel(
            name='Adelanto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField()),
                ('descripcion', models.CharField(blank=True, default='Adelanto', max_length=255)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('gimnasio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adelantos_profesor', to='gimnasio.gimnasio')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adelantos', to='gimnasio.profesor')),
            ],
            options={
                'verbose_name': 'Adelanto',
                'verbose_name_plural': 'Adelantos',
                'db_table': 'Adelantos',
            },
        ),
        migrations.AddField(
            model_name='venta',
            name='profesor',
            field=models.ForeignKey(blank=True, help_text='Profesor al que se le vendió el producto (cuenta como crédito a su favor)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_a_profesor', to='gimnasio.profesor'),
        ),
    ]
