# Generated by Django 5.1.4 on 2026-03-04 16:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0028_profesores_adelantos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField()),
                ('efectivo', models.FloatField(blank=True, default=0, null=True)),
                ('transferencia', models.FloatField(blank=True, default=0, null=True)),
                ('tarjeta_credito', models.FloatField(blank=True, default=0, null=True)),
                ('nombre_titular', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.CharField(blank=True, default='Pago profesor', max_length=255)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('gimnasio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos_profesor', to='gimnasio.gimnasio')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='gimnasio.profesor')),
            ],
            options={
                'verbose_name': 'Pago Profesor',
                'verbose_name_plural': 'Pagos Profesor',
                'db_table': 'PagosProfesor',
            },
        ),
    ]
