# Generated by Django 5.1.4 on 2026-04-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0029_pago_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='celular',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
