# Generated by Django 5.2.7 on 2026-06-09 23:25

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0033_quitar_mensualidades_plantilla'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='auth_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='socio_perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('notas', models.TextField(blank=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas', to='gimnasio.categoriamensualidad')),
                ('gimnasio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas', to='gimnasio.gimnasio')),
            ],
            options={
                'verbose_name': 'Rutina',
                'verbose_name_plural': 'Rutinas',
                'db_table': 'Rutinas',
            },
        ),
        migrations.CreateModel(
            name='ProgramacionEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia', models.CharField(choices=[('diaria', 'Diaria'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], default='semanal', max_length=20)),
                ('dias_semana', models.CharField(blank=True, help_text='Días 0-6 (lun-dom), separados por coma. Ej: 0,2,4', max_length=30)),
                ('dia_mes', models.PositiveSmallIntegerField(blank=True, help_text='Día del mes (1-31) si es mensual', null=True)),
                ('activa', models.BooleanField(default=True)),
                ('ultimo_envio', models.DateField(blank=True, null=True)),
                ('gimnasio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programaciones_rutina', to='gimnasio.gimnasio')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programaciones', to='gimnasio.rutina')),
            ],
            options={
                'verbose_name': 'Programación de envío',
                'verbose_name_plural': 'Programaciones de envío',
                'db_table': 'ProgramacionesEnvioRutina',
            },
        ),
        migrations.CreateModel(
            name='EjercicioRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('series', models.PositiveIntegerField(default=3)),
                ('repeticiones', models.CharField(default='12', max_length=50)),
                ('peso', models.CharField(blank=True, max_length=80)),
                ('descanso', models.CharField(blank=True, max_length=80)),
                ('notas', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='gimnasio.rutina')),
            ],
            options={
                'verbose_name': 'Ejercicio de rutina',
                'verbose_name_plural': 'Ejercicios de rutina',
                'db_table': 'EjerciciosRutina',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RutinaEntregada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_publicacion', models.DateField(default=datetime.date.today)),
                ('programacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas', to='gimnasio.programacionenvio')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='gimnasio.rutina')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas_entregadas', to='gimnasio.socio')),
            ],
            options={
                'verbose_name': 'Rutina entregada',
                'verbose_name_plural': 'Rutinas entregadas',
                'db_table': 'RutinasEntregadas',
                'ordering': ['-fecha_publicacion', '-id'],
                'unique_together': {('socio', 'rutina', 'fecha_publicacion')},
            },
        ),
    ]
