# Generated by Django 5.2.7 on 2026-06-10 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0034_rutinas_portal_socio'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriamensualidad',
            name='usa_turnos',
            field=models.BooleanField(default=False, help_text='Si está activo, los socios de esta categoría reservan turnos por día y hora.'),
        ),
        migrations.CreateModel(
            name='HorarioTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora', models.TimeField()),
                ('cupo_maximo', models.PositiveIntegerField(default=12)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_turno', to='gimnasio.categoriamensualidad')),
                ('gimnasio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_turno', to='gimnasio.gimnasio')),
            ],
            options={
                'verbose_name': 'Horario de turno',
                'verbose_name_plural': 'Horarios de turno',
                'db_table': 'HorariosTurno',
                'ordering': ['dia_semana', 'hora'],
                'unique_together': {('categoria', 'dia_semana', 'hora')},
            },
        ),
        migrations.CreateModel(
            name='ReservaTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('horario_turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='gimnasio.horarioturno')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_turno', to='gimnasio.socio')),
            ],
            options={
                'verbose_name': 'Reserva de turno',
                'verbose_name_plural': 'Reservas de turno',
                'db_table': 'ReservasTurno',
                'ordering': ['fecha', 'horario_turno__hora'],
                'unique_together': {('socio', 'horario_turno', 'fecha')},
            },
        ),
    ]
