# Generated by Django 5.2.7 on 2026-06-10 18:34

from django.db import migrations, models


def migrar_categorias_a_m2m(apps, schema_editor):
    HorarioTurno = apps.get_model('gimnasio', 'HorarioTurno')
    ReservaTurno = apps.get_model('gimnasio', 'ReservaTurno')
    keepers = {}
    for h in HorarioTurno.objects.select_related('categoria').order_by('pk'):
        key = (h.gimnasio_id, h.dia_semana, str(h.hora))
        if key not in keepers:
            keepers[key] = h
            if h.categoria_id:
                h.categorias.add(h.categoria_id)
        else:
            keeper = keepers[key]
            if h.categoria_id:
                keeper.categorias.add(h.categoria_id)
            if keeper.cupo_maximo < h.cupo_maximo:
                keeper.cupo_maximo = h.cupo_maximo
                keeper.save(update_fields=['cupo_maximo'])
            for reserva in ReservaTurno.objects.filter(horario_turno_id=h.pk):
                existe = ReservaTurno.objects.filter(
                    socio_id=reserva.socio_id,
                    horario_turno_id=keeper.pk,
                    fecha=reserva.fecha,
                ).exists()
                if not existe:
                    reserva.horario_turno_id = keeper.pk
                    reserva.save(update_fields=['horario_turno_id'])
            h.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0035_turnos_por_categoria'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horarioturno',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='horarioturno',
            name='categorias',
            field=models.ManyToManyField(related_name='horarios_turno', to='gimnasio.categoriamensualidad'),
        ),
        migrations.RunPython(migrar_categorias_a_m2m, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='horarioturno',
            name='categoria',
        ),
        migrations.AlterUniqueTogether(
            name='horarioturno',
            unique_together={('gimnasio', 'dia_semana', 'hora')},
        ),
    ]
