# Copiar a: /etc/nginx/sites-available/facugym
# ln -s /etc/nginx/sites-available/facugym /etc/nginx/sites-enabled/
# certbot --nginx -d facugym.sistemgympro.com

upstream gym_app {
    server unix:/run/gym.sock fail_timeout=0;
}

server {
    listen 80;
    listen [::]:80;
    server_name facugym.sistemgympro.com;

    location / {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;
        proxy_pass http://gym_app;
    }

    location /static/ {
        alias /var/www/gym/staticfiles/;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }
}
